spring.datasource.url=jdbc:mysql://mysql:3306/car_sharing?useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQLDB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRATION = 3600000

STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_URL=http://localhost:8080
TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
